### ISSUE TITLE
[BUG] Weird axis ticks

### ISSUE THREAD

**Issue by andrewc910** [styd/apexcharts.rb#23]
**Describe the bug**
As per our conversation on reddit, here is the problem i am having. The graph is showing the percentage of customers that return after X amount of visits. Hash keys are the X amount of visits, hash values are the percentage of returning customers. 

Context: 
Final return value is the hash i put down below. Using a line chart with options labeling the x and y axis. All pretty simple stuff. It looks like apex is averaging the numbers between the first and last which makes sense but doesn't actually look all that nice.

Series Data:
{1=>99.69,
 5=>99.0,
 10=>98.22,
 25=>95.89,
 50=>91.64,
 100=>83.27,
 200=>66.78,
 300=>50.06,
 400=>33.13,
 500=>17.02}

What I expected:
The keys to be the X labels. 

Screenshot of output:
https://ibb.co/MDgsbwR  (First time using this image hoster, if it breaks, let me know!)

**Comment by styd** [comment]
Hi @andrewc910, thank you for reporting the issue.

I'll look into it later when I have time.
Don't worry about the hosted image. I already downloaded it. ;-)

**Comment by styd** [comment]
@andrewc910, after testing it myself, I never encounter the condition where the `xaxis` tick has a long fractional digits. The fractional digits I got is only one digit after the comma.

The way apexcharts finds equal intervals is already good enough I think.
If your data is of consistent intervals and the `xaxis` values are round numbers (which is usually the case) then the tick points will look nice.

For your rather unusual case, you need to specify how many ticks (`tickAmount`) you want and the starting point (`min`) in order to make it look nice.
The following is a gif image of two screenshots with the first image is the chart without any options (what you currently have) and the second is with this options:
```ruby
 {xaxis: {min: 0, tickAmount 10}, yaxis: {max: 100}}  
```
![issue-23](https://user-images.githubusercontent.com/8341867/62140916-f2c20f00-b315-11e9-8c87-79de108d4ac6.gif)

And then the `yaxis` doesn't look nice. But at least now you know how to fix it right?
I hope this solves your problem.

**Comment by styd** [comment]
I consider your case is special. Therefore, cannot use the default settings and need special options.
