### ISSUE TITLE
Tooltip Formatter option

### ISSUE THREAD

**Issue by daveomcd** [styd/apexcharts.rb#31]
I think this is mentioned in #25 , but is it possible to add a formatter for tooltips?  Or is there a suggested workaround?  I was hoping to format my value as currency.

**Comment by styd** [comment]
Currently, there is no way to add formatter function to chart options hash. One of the hackey way I know is to use JS to [updateOptions](https://apexcharts.com/docs/methods/#updateOptions) right after you render the chart.

As you know, I've already requested a feature that adds `prefix` and `suffix` as a replacement for `formatter`. Still no reply yet. But I'm currently trying out ways to support this from ruby side. Hopefully, I can work it out on the next release. But you should know that this is one of my top priority.

**Comment by daveomcd** [comment]
Would prefix and suffix help in cases like formatting a string from 45000 to $45,000 ?  Where it needs a comma as well?  Thanks for the updateOptions workaround I'll look into that.  I really appreciate all the work you've put into this it's helped me out greatly.

**Comment by styd** [comment]
They will not help of course. But as far as I know, this problem exists in other ruby charting libraries (e.g. chartkick) as well. That's why I'm working on a way to make functionable json from ruby hash. I will try to implement this within this week.

Thank you for using this gem and don't forget to spread the word about this. I need to know if this is useful to other people as well and also need as many contributions as possible (PRs, feature requests, bug reports, code reviews, etc.) to keep this gem updated with prioritized features.

**Comment by styd** [comment]
@daveomcd, [this](https://github.com/styd/functionable-json) works on my app. Can you try using it in your app?

**Comment by styd** [comment]
Technically, it should work for adding simple function.

**Comment by daveomcd** [comment]
Love it thanks @styd ! Sorry for taking me awhile to get back to you on this.

**Comment by styd** [comment]
You're welcome. No worries. Let me know if you think another functionality should be added.
